public with sharing class DealerNOProgBarCompController {
/*********************************************************************************
    Name         : DealerNOProgBarCompController (Dealer New Order Progress Bar Component Controller)
    Created By   : 
    Company Name : ViaSat, Inc.
    Project      : Dealer Pages
    Created Date : 
    *********************************************************************************/
    
    //Controls which circle is displayed as active on the Dealer New Order Pages
}