/**************************************************************************************************************
Name         : DealerSettingsResourceCompController 
Created By   : Jim Tunney
Modified By  : 
Project      : Dealer Portal
Created Date : 18 Nov 2015
Modified Date: 
Usages       : Controller for DealerSettingsResourcesComponent, a component to the VF page: DealerSettingsPage
***************************************************************************************************************/ 
public with sharing class DealerSettingsResourceCompController {
	public DealerComponenttoController componentToPage{get; set;}
    
    public pageReference checkAvailButton() {
        //CODE TO HANDLE BEAM LOOKUP HERE
        
        return null;
    }
}