/**************************************************************************************************************
Name         : ITSMSFormsComponentController 
Created By   : Dianna Guilinger - Slalom 
Description  : Controller for VF Component ITSMSFolderShare
             : Obtains passed parameters, manages page action
***************************************************************************************************************/
public with sharing class ITSMSFormsComponentController extends ITSMSComponentControllerBase {

    public ITSMSFormsComponentController () {
    }
}