/**************************************************************************************************************
Name         : ITSMSSupportCenterContactUsController 
Created By   : Dianna Guilinger - Slalom 
Description  : Controller for VF Component ITSMSSupportCenterContactUs
             : Obtains passed parameters, manages page action
***************************************************************************************************************/
public class ITSMSSupportCenterContactUsController extends ITSMSPageControllerBase{
    
    // initialize page - check for category, id parameters
    public ITSMSSupportCenterContactUsController()  {
        setNavigationElements();
    }
        
}