/**************************************************************************************************************
Name         : ITSMSTemplateController 
Created By   : Dianna Guilinger - Slalom 
Description  : Controller for VF Template
***************************************************************************************************************/
public class ITSMSTemplateController extends ITSMSPageControllerBase {
    public ITSMSTemplateController()  {
       setNavigationElements();
    }

}