@IsTest public class KBDAPRemovaltest { 
    /*public static testmethod void test1() {
        KBDAPRemoval controller = new KBDAPRemoval();    
        controller.accountName = 'a';
        controller.details = 'd';
        String inital = 'MKanike';
        String accNameClean = controller.accountNameClean;
        String detClean = controller.detailsClean;
		String liveAgentDomain = controller.liveAgentDomain;
        
        controller.actionContinue();
        controller.goBack();
        controller.chatNow();
        controller.CleanForJavascript(inital);
    }*/
}