@IsTest public with sharing class KBEscalateToCorporateCaretest {   
   /* public static testmethod void Test1() {
        KBEscalateToCorporateCare ecc = new KBEscalateToCorporateCare();
        String initial = 'MKanike';
        ecc.accountName = 'a';
        ecc.name = 'n';
        ecc.description = 'd';
        ecc.ticketNumber = 's';
        
        String accClean = ecc.accountNameClean; 
        String nameClean = ecc.nameClean;
        String ticketClean = ecc.ticketNumberClean;
        String descClean = ecc.descriptionClean;
        String liveAgentDomain = ecc.liveAgentDomain;
        
        ecc.goBack();
        ecc.actionContinue();
        ecc.chatNow();
        ecc.CleanForJavascript(initial);
        
    }*/
}