/*
    Controller for the useful links component.
    Extracts and displays the useful links
        
    **********************************************************
    Audit History
    **********************************************************
    4/13/2013    Lucian Ciobanu      Created
    **********************************************************  
*/
public with sharing class KBHomeUsefulLinks {

    /*public boolean inConsole { get; set; }

    // Useful Links 
    public List<UsefulLinks__c> usefulLinks { get; set; }

    public KBHomeUsefulLinks() {
    
        inConsole = false;
        if (!String.isEmpty(ApexPages.currentPage().getParameters().get('isdtp')))
            inConsole = true;
            
        // Extract useful links from custom settings
        usefulLinks = [SELECT Id, URL__c, URLTitle__c FROM UsefulLinks__c];
        
    }
    
    @IsTest public static void test1() {
        KBHomeUsefulLinks controller = new KBHomeUsefulLinks();
    }
    */
}